
import Sidebar from '@/components/shared/Sidebar';
import React from 'react';


export const metadata = {
    title: 'dashboard',
    description: 'Generated by create next app',
}



const DashboardLayout = ({ children }) => {
    return (
        <div className='flex'>


            <div className='w-full'>    {children}</div>

        </div>
    );
};

export default DashboardLayout